### ISSUE TITLE
App doesn't show non-responsive council warning

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet-mobile#215] opened 2016-04-13 15:21 UTC
The main site displays a message when a user starts to report a problem within the area of a council that's refused to accept reports via FixMyStreet. (Important message [XXXX] Council doesn’t accept reports from third party reporting sites such as FixMyStreet. We can make your report public, but we can’t send it to the council.)

The app just lets users make a report, with no warning that it isn't going to be sent anywhere.

**Comment by dracos** [comment] 2016-04-20 19:28
https://twitter.com/gears/status/721603791104122880 – it is okay for two tier councils, the issue is with a one-tier council, it looks like. I think we can do this server side, hopefully.

**Comment by dracos** [comment] 2016-04-22 12:02
Fixed by https://github.com/mysociety/fixmystreet/commit/beee3223643a5611ee4aaa92e0b60fae7a13d839

**Closed by dracos** 2016-04-22 12:02 UTC
