### ISSUE TITLE
Issues testing new release on Android

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#282] opened 2019-10-02 12:56 UTC
- [x] 1. Cancel button on front page no longer works (with geolocation off). turned on location, still nothing. had to close app and restart to kick it checking for location, then I got a map
- [x] 2. pinch to zoom out you can see some cobrand code printed behind it until the tiles load? "if type == Bing" I think I saw
- [x] ~3. ordering of categories in westminster is weird. things without groups then things with maybe? even though many (e.g. abandoned bike) only has the one category under it~ See #283.
- [ ] 4. the emergency message stuff all seems to work fine - wondered if the island roads example should appear under where I've just changed something rather than at the top? Dunno
- [x] 5. geocoding seems very slow compared to website (i'm on same wifi). in fact, it's just hung on a search for northampton, no way to get out of it. yeah, reproducible - geocoding disambiguation broken perhaps?

**Comment by davea** [comment] 2019-10-03 10:37
2 was due to the `index.html` template not being rendered correctly; fixed by c9d5f481fb140bb70c95bb7a08e4e53228ff0830.

1 & 5 I can't reproduce - what version of Android, screen size, etc? Can you narrow it down to specific steps?

4: it should scroll you to the top of the page so you can see the message.

3: Agree that this isn't ideal, but have broken it out into its own ticket (#283) as it's not an Android-specific issue.

**Comment by dracos** [comment] 2019-10-03 10:44
Android 7.1.2, screen size 360x640 I think. Specific steps:
1. Start the app from nothing with geolocation turned off? :) I get the "Finding your location" and cancel button, and cancel button no longer does anything.
5. Start app from nothing (with geolocation on), when search box appears, search for Northampton. Spinner sits there for ever, nothing happens.

**Comment by davea** [comment] 2019-10-04 09:17
1 & 5 were also a knock-on effect of 2, fixed.

4 is by design. We could revisit this when the app is redesigned.

**Closed by davea** 2019-10-04 09:17 UTC
Labels: bug
