### ISSUE TITLE
Back button (goes back or) closes the app

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet-mobile#193] opened 2015-01-21 20:27 UTC
It seems to be pretty standard for Android apps that pressing the back button initially/eventually will close the app. However, fixmystreet-mobile will not close when the back button is pressed.

I think this would be convenient for users, so they wouldn't have to hold the "app" button, locate the app, and slide it off the screen, in order to close the app.

Thank you!

**Comment by MyfanwyNixon** [comment] 2015-06-05 08:22
Via Twitter:

> Pleased to see there is a Fix My Street app, unfortunately it's annoying because there is no back button & you can't get rid.

Then

> Android, Galaxy S5. I left feedback on the appstore too before uninstaling. Others have too. It's unusable the way it is.

And

>  I use Fix My Street a lot, the app would be brilliant for me. Can you let me know when fixed pls?

**Comment by Gemmamysoc** [comment] 2015-06-05 09:26
User feedback: 

"The back button does not work.  Android app used on Samsung Galaxy S5."

**Comment by DeeHants** [comment] 2016-04-20 23:13
Same here. The back button works most of the time, UNTIL you find yourself on the FMS website (e.g. after clicking a link) rather than the inbuilt pages.
From this point on, there is nothing you can do to close it short of killing it.

**Comment by dracos** [comment] 2016-04-22 12:07
There appear to be two separate bugs here, so I've separated out the second one (not being able to get out of a website view, which I can replicate) into a different ticket: #218
The original bug here appears to be that the back button does not work *at all* to go back or exit the app, which I am unable to replicate on the Android phone I have; back works for me, and on the first page does exit the app.
Two Galaxy S5s in the above comments, so that sounds like one worth testing on and seeing what's happening/why default back button isn't appearing.
Hopefully we will update our framework soon and we can retest this then and see if it's hopefully fixed!

**Comment by abimysoc** [comment] 2016-04-22 12:14
Doesn't happen on my Galaxy S5, where the back button either goes back or closes the app exactly as expected.

**Comment by DeeHants** [comment] 2016-04-22 12:19
I can't reproduce the back "not working at all" issue in the main app on an Xperia Z3, and can try with a Samsung S4 tonight.

**Comment by dracos** [comment] 2016-04-22 12:20
@abimysoc How weird. I guess updating the framework might change all this anyway.
Thanks @DeeHants!

**Comment by dracos** [comment] 2016-05-11 08:26
Hopefully this is all fixed by the updated app.

**Closed by dracos** 2016-05-11 08:26 UTC
Labels: 1 - contender
