### ISSUE TITLE
Switch GPS off when user has switched away from app

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet-mobile#61] opened 2013-07-22 08:41 UTC
Default android app behaviour is to use the GPS only when the user is looking at an app. If they move to another app, or the phone locks, GPS must be switched off to save battery.

**Comment by Gemmamysoc** [comment] 2015-01-28 12:09
User feedback:

Not about site, but there is no option for reporting app problems.
Google Play app reports are primarily to Google and not guaranteed
to be forwarded to the developer, so this duplicates my GP report.

I have installed the app, but it consumes massive amounts of battery
even when the app has lost focus, probably because the GPS remains
enabled. Also, the app does not quit on leaving the app with the
system Back button. To quit, I have the force a stop.

I will uninstall the app, because I cannot risk postponing
completion of a report only to find that my battery is flat.

**Comment by Gemmamysoc** [comment] 2015-02-27 11:18
User feedback: 

"Your iOS app wants to know my location always instead of just when
I'm using it. You really don't need to know that."

**Comment by dracos** [comment] 2016-04-26 16:21
Dupe of #213

**Closed by dracos** 2016-04-26 16:21 UTC
Labels: 4 - awaiting review
